### ISSUE TITLE
Shifting and speak, dosen't trigger vibrations when the option is in true

### ISSUE THREAD

**Issue by Kysha7** [iGalaxyYT/voicechat-interaction-paper#2]
Bug description
In the config file you can choose if "sneak_interaction" should trigger vibrations or not. I choose put that in "true", but when I speak while shifting, donsen't trigger.

Steps to reproduce the issue
Turn the option "sneak_interaction" into "true" and then shift and speak normal, vibrations donsen't show and sensor don't do sound.

Expected behavior
With the option in true, speak while shifting should trigger the sensor.

Log files
There is no logs. In this case, the plugin work almost perfect, I can press the wisper button and no vibration show up, I can speak normal and hear me

Versions
Version of the server "purpur-1.19-1718"
Version of the plugin voicechat-interaction-paper-1.0.0

**Comment by ayleafs** [comment]
This is caused as a result of the developer firing the `STEP` GameEvent in order to actually alert the warden. The simple fix is to change the GameEvent to a `BLOCK_PLACE` and then pass through the player's location. @iGalaxyYT

**Comment by iGalaxyYT** [comment]
> This is caused as a result of the developer firing the `STEP` GameEvent in order to actually alert the warden. The simple fix is to change the GameEvent to a `BLOCK_PLACE` and then pass through the player's location. @iGalaxyYT

Thanks for the heads up, I've replaced it with the `PRIME_FUSE` GameEvent for frequency parity with the official mod instead of `BLOCK_PLACE`. See https://github.com/iGalaxyYT/voicechat-interaction-paper/commit/e6cbbaf8285a2e6c8597590c665313275db489f3

**Comment by ayleafs** [comment]
This might be worth mentioning:

I see you've changed the player from `bukkitPlayer` to `null`. I think it is important to make sure that the event is triggered by the player, since the Warden _does keep_ NBT data relating to specific players and how angry it is at them.
