### ISSUE TITLE
Connection Issues with this plugin on MC Version 1.19.2

### ISSUE THREAD

**Issue by MrPresidentWhite** [iGalaxyYT/voicechat-interaction-paper#3]
is also the minecraft version 1.19.2 supported? when i installed this plugin, i coudlnt connect to voicechat anymore.

- Paper Version: 1.19.2
- Simple VC Version: 1.19.2 | 2-2.3.10
- Java Version: 17.0.4
- vc interaction paper version: latest

**Comment by iGalaxyYT** [comment]
I've been running it fine on a Paper 1.19.2 server w/ SVC 2.3.6 (there shouldn't be any breaking changes in 2.3.10) for at least 2 months. Are you sure you could connect to SVC beforehand?

**Comment by MrPresidentWhite** [comment]
I think I figured out what was wrong now. after a disconnect, my client with the mod somehow can no longer connect to the server. I have to restart the game completely so that the voice mod can connect to the server again. but why that is I have no idea

**Comment by iGalaxyYT** [comment]
Weird. I'll try recreating this when I'm at my PC.

**Comment by iGalaxyYT** [comment]
Update: Wasn't able to recreate this. I think this might be an issue with SVC itself and your client setup. See if this occurs without my plugin and then report to the SVC repo. Will reopen if I find anything new on the issue.

**Comment by MrPresidentWhite** [comment]
i have posted a more detailed description of my server and client setup if you are interested. [Simple Voice Chat Issue #481](https://github.com/henkelmax/simple-voice-chat/issues/481)
