### ISSUE TITLE
[Suggestion] Add feature to toggle this for players.

### ISSUE THREAD

**Issue by TomSipsOnCurry** [iGalaxyYT/voicechat-interaction-paper#4]
On our server, we want this to be completely optional and off by default. We don't want people to die from wardens because they weren't mute or didn't know this was a feature.

**Comment by iGalaxyYT** [comment]
Added in v1.2.0 (https://github.com/iGalaxyYT/voicechat-interaction-paper/releases/tag/v1.2.0)
