### ISSUE TITLE
Could you make your Plugin available for Aternos?

### ISSUE THREAD

**Issue by Minoxxe** [iGalaxyYT/voicechat-interaction-paper#6]
Hello,
I was trying to submit your Plugin in the Aternos "Plugin suggestion" section, but unfortunately Github website is not supported. I already tried to contact Aternos support for help, but they gave me this following solution. If it doesn't bother you too much, I wanted to ask you if you could upload your Plugin to one of these websites (actually I have no idea which is the appropriate website for plugins, maybe the third one):

curseforge.com
dev.bukkit.org
spigotmc.org
poggit.pmmp.io
modrinth.com

If you have already done this, could you send me the link, so that I can submit the plugin? Thank you.

**Comment by iGalaxyYT** [comment]
Hi, I've already made it available on Modrinth at https://modrinth.com/plugin/voice-chat-interaction-paper.

**Comment by Minoxxe** [comment]
I'm sorry, I didn't see it. Tank you so much!
